---
title: "作業2"
output: 
  html_document: 
    toc: true
    toc_depth: 1
    number_sections: false
    toc_float:
      collapsed: true
      smooth_scroll: false
params:
  name: ["黃鉦翔","林應廷","張又方","劉婷軒"]
  id: [710761121,710761129,710761103,710761130]
  group: "teamG"
  url: ""
---
請依狀況更改上面的name,id及group（分別代表組員姓名，學號及組號），但請勿更改下面三行的設定。  

***

姓名：`r params$name`  
學號：`r params$id`  
組號：`r params$group`  
網頁：`r params$url` 

***
```{r setup, include=FALSE}

```

##1-1

$Y=Y_{-p}+{\beta}^\star P$ \
 $=E(Y|P)= E(Y_{-p})+{\beta}^\star P|P)$ \
 $=E[E(Y_{-p}|rincome)+\tilde{\epsilon}|P]+{\beta}^{\star}P$ \
 $=E(2+3rincome+\tilde{\epsilon}|P)+{\beta}^{\star}P$ \
 $=2+3E(rincome|P)+E(\tilde{\epsilon}|P)+{\beta}^{\star}P$ \
 $=2+\beta^{\star}P$ \
 其中$rincome ⊥ P$則 $E(rincome|P)=0$ \
 $\tilde{\epsilon}⊥ P則 E(\tilde{\epsilon}|P)=0$ \
 
 由此過程可以得知，$E(Y|P)$其中$P$的係數為$\beta^*$

##1-2


$E(Y|P)=E(2+3rincome|P)+E(\tilde{\epsilon}|P)+{\beta^\star}P$ \
      $=E(2+3rincome|P)+0+{\beta^\star}P$ \
      $=2+3E(rincome|P)+{\beta^\star}P$ \
      $=2+3(0.5+P)+{\beta^\star}P$ \
      $=3.5+(3+{\beta^\star})P$ \
      由此過程可以得知，$E(Y|P)中P的係數不等於{\beta^\star}$ \
 \

$E(Y|P,rincome)=E(Y_{-P}+{\beta^\star}P|P,rincome)$ \
              $=E[E(Y_{-P}|rincome)+\tilde{\epsilon}|P,rincome]+{\beta^\star}P$ \
              $=E(Y_{-P}|rincome)+E(\tilde{\epsilon}|P,rincome)+{\beta^\star}P$ \
              $=2+3rincome+0+{\beta^\star}P$ \
              由此過程可以得知，$E(Y|P,rincome) 中P的係數為{\beta^\star}$

##1-3

$E(Y|P)=E(Y_{-p}+\beta^*P|P)$ \
      $=E[E(Y_{-p}|rincome)+\tilde{\epsilon}|P]+\beta^*P$ \
      $=E(2+3rincome|P)+E(\tilde{\epsilon}|P)+\beta^*P$ \
      $=2+3E(rincome|P)+0.5+2P+\beta^*P$ \
      $=2+3(0.5+P)+0.5+2P+\beta^*P$ \
      $=4+(5+\beta^*)P$  \
      由此過程可以得知，其中$5+\beta^*$不等於$\beta^*$ \
 \
$E(Y|P,rincome)=E(Y_{-p}+\beta^*P|P,rincome)$ \
              $=E(E(Y_{-p}|rincome)+\tilde{\epsilon}|P,rincome]+\beta^*P$ \
              $=2+3rincome+E(\tilde{\epsilon}|P,rincome)+\beta^*P$ \
              $=2+3rincome+0.5+2P+\beta^*P$ \
              $=2.5+3rincome+(2+\beta^*)P$  \
              由此過程可以得知，其中$2+\beta^*$不等於$\beta^*$


##1-4

$E(Y|P_z,rincome)=E(Y_{-p}+\beta^*P|P_z,rincome)$ \
                $=E[E(Y_{-p}|rincome)+\tilde{\epsilon}|P_z,rincome]+E(\beta^*P|P_z,rincome)$ \
                $=2+3rincome+\beta^*P_z$ \
                
其中:  \
$E(\tilde\epsilon|P_z,rincome)=E[Y_{-p}-E(Y_{-p}|rincome)|P_z,rincome]$ \
                             $=E(Y_{-p}|P_z,rincome)-E(Y_{-p}|P_z,rincome)=0$ \
                             
由此過程可以得知，$E(Y|P_z,rincome)$其中$P_z$的係數為$\beta^*$

##1-5

$E(Y|P,rincome,Z)=E(Y_{-p}+{\beta}^{\star}p|p,rincome,Z)$ \
                $=E[E(Y_{-p}|rincome)+\tilde{\epsilon}|p,rincome,Z]+\beta^{\star}p$ \
                $=2+3rincome+E(\tilde{\epsilon}|p,rincome,Z)+\beta^{\star}p$ \
                $=2+3erincome+\beta^{\star}$ \
                \
                
                其中 \
                $E(\tilde{\epsilon}|p,rincome,Z)=E[Y_{-p}-E(Y_{-p}|rincome|p,rincome,Z)]$ \
                $=E[Y_{-p}|p,rincome,Z]-E(Y_-p|rincome)|p,rincome,Z]$ \
                $=E(Y_{-p}|p,rincome,Z)-E(Y_-p|p,rincome,Z)=0$ \
                由此過程可以得知，$E(Y|P,rincome,z)$其中$P$的係數不會為$\beta^*$

